language: python
python:
  - "3.6"

install:
  - pip install Cython --install-option="--no-cython-compile"
  - pip install -r test_requirements.txt
  - pip install --progress-bar off torch
  - pip install .
# run tests
script: nosetests
